GET http://localhost:8080 HTTP/1.1

###
GET http://localhost:8080/gardening HTTP/1.1

### CREATE PLANT 
POST http://localhost:8080/gardening HTTP/1.1
content-type: application/json

 {
   "plantName": "Tomato",
   "hoursOfSun": "6-8 hours",
   "goodNeighbors": "Broccoli, Peppers, Celery, Asparagus, Cabbage",
   "badNeighbors": "Corn, Rosemary, Dill, Chili Peppers, Peas, Potatoes, Fennel",
   "startIndoors": "April 15",
   "transplantOutdoors": "May 20"
 }

### CREATE PLANT THROUGH RENDER
POST https://gardening-app.onrender.com/gardening HTTP/1.1
content-type: application/json

 {
   "plantName": "Tomato",
   "hoursOfSun": "6-8 hours",
   "goodNeighbors": "Broccoli, Peppers, Celery, Asparagus, Cabbage",
   "badNeighbors": "Corn, Rosemary, Dill, Chili Peppers, Peas, Potatoes, Fennel",
   "startIndoors": "April 15",
   "transplantOutdoors": "May 20"
 }

### EDIT PLANT THROUGH RENDER
PUT https://gardening-app.onerender.com/gardening/6468f3764eb079058b534465 HTTP/1.1
content-type: application/json

### DELETE PLANT ON RENDER
DELETE https://gardening-app.onrender.com/gardening HTTP/1.1

###
GET https://gardening-app.onrender.com/gardening HTTP/1.1

###
GET https://gardening-app.onrender.com/gardening HTTP/1.1

